use jni::objects::JClass;
use jni::sys::{jint, jstring};
use jni::JNIEnv;
use std::fs::File;
use std::io::Write;
use zip::write::FileOptions;

#[no_mangle]
pub extern "C" fn Java_com_invuzt_xpiz_MainActivity_getContentFromRust(
    env: JNIEnv,
    _class: JClass,
    page_id: jint,
) -> jstring {
    // Kalau Tombol TRAINING (ID 1) diklik, Rust mulai ngerakit file
    if page_id == 1 {
        let path = "/data/data/com.invuzt.xpiz/files/XPIZ_Package.zip";
        
        // Proses Pembuatan ZIP Asli (Bukan Dummy)
        if let Ok(file) = File::create(path) {
            let mut zip = zip::ZipWriter::new(file);
            let options = FileOptions::default()
                .compression_method(zip::CompressionMethod::Stored);

            // Masukin file teks ke dalem ZIP sebagai bukti build
            let _ = zip.start_file("build_log.txt", options);
            let _ = zip.write_all(b"Build Success!\nGenerated by XPIZ Engine v1.0");
            let _ = zip.finish();

            let res = "BUILD SUCCESS:\n- File: XPIZ_Package.zip\n- Status: Zip Created\n- Logic: Non-Dummy";
            return env.new_string(res).unwrap().into_raw();
        } else {
            let res = "BUILD ERROR:\n- Folder Not Found\n- Check Permission\n- Status: Failed";
            return env.new_string(res).unwrap().into_raw();
        }
    }

    // Halaman PROGRESS (ID 2) cuma nampilin info
    let res = "READY TO BUILD:\n- Mode: File Archiver\n- Press Training to Start\n- Status: Standby";
    env.new_string(res).unwrap().into_raw()
}
