[package]
name = "xpiz_core"
version = "0.1.1"
edition = "2021"

[lib]
name = "xpiz_core"
crate-type = ["staticlib", "cdylib"]

[dependencies]
jni = "0.21.1"
# Pustaka untuk mengevaluasi ekspresi matematika string
evalexpr = "8.1"

[profile.release]
opt-level = 'z'
lto = true
codegen-units = 1
panic = 'abort'
strip = true
